name: 'S3 Bucket Upload Action'
description: 'Action for uploading assets to an s3 bucket'
branding:
  icon: 'upload'
  color: 'orange'
inputs:
  keyid:
    description: "keyid"
    required: true
  accesskey:
    description: "accesskey"
    required: true
  region:
    description: "region"
    required: true
  bucket:
    description: "bucket"
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.keyid }}
    - ${{ inputs.accesskey }}
    - ${{ inputs.region }}
    - ${{ inputs.bucket }}
